//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuLivroDeReceitas.CrossCutting.Resources.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeuLivroDeReceitas.CrossCutting.Resources.Infrastructure.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login não encontrado..
        /// </summary>
        public static string Authenticate_Error_NotFound {
            get {
                return ResourceManager.GetString("Authenticate_Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres da password não pode ser {0}, deve ficar entre {1} e {2}..
        /// </summary>
        public static string LoginValidator_Error_CharactersPassword {
            get {
                return ResourceManager.GetString("LoginValidator_Error_CharactersPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email é invalido..
        /// </summary>
        public static string LoginValidator_Error_EmailIsInvalid {
            get {
                return ResourceManager.GetString("LoginValidator_Error_EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email é obrigatório..
        /// </summary>
        public static string LoginValidator_Error_EmailIsRequired {
            get {
                return ResourceManager.GetString("LoginValidator_Error_EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password é obrigatória..
        /// </summary>
        public static string LoginValidator_Error_PasswordIsRequired {
            get {
                return ResourceManager.GetString("LoginValidator_Error_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login não encontrado..
        /// </summary>
        public static string PasswordChangeByForgot_Error_UserNotFound {
            get {
                return ResourceManager.GetString("PasswordChangeByForgot_Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na criação do usuário, det: {0}.
        /// </summary>
        public static string RegisterUser_Error_CreateUser {
            get {
                return ResourceManager.GetString("RegisterUser_Error_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login encontrado..
        /// </summary>
        public static string RegisterUser_Error_Found {
            get {
                return ResourceManager.GetString("RegisterUser_Error_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na alteração do usuário, det: {0}.
        /// </summary>
        public static string UserChange_Error_UpdateUser {
            get {
                return ResourceManager.GetString("UserChange_Error_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login não encontrado..
        /// </summary>
        public static string UserChange_Error_UserNotFound {
            get {
                return ResourceManager.GetString("UserChange_Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do telefone celular fora do padrão. Método:{0}. Número:{1}.
        /// </summary>
        public static string UserChangeValidator_Error_NonStandardCellNumber {
            get {
                return ResourceManager.GetString("UserChangeValidator_Error_NonStandardCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone celular é obrigatório..
        /// </summary>
        public static string UserValidator_Error_PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("UserValidator_Error_PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário é obrigatório..
        /// </summary>
        public static string UserValidator_Error_UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserValidator_Error_UserNameIsRequired", resourceCulture);
            }
        }
    }
}
